# lightning.pytorch==2.0.4
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 90
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: true
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: true
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 60
  default_root_dir: ../tests/m2m_sun397/
ckpt_path: last
model:
  class_path: module.M2mModule
  init_args:
    rej_prob: 0.999
    attack_iters: 10
    regul_param: 0.5
    step_size: 0.1
    misclass_bound: 0.9
    checkpoint_path: ../results/erm_sun397/lightning_logs/version_20/checkpoints/epoch=89-step=31320.ckpt
    num_classes: 397
    bb_name: ResNet
    bb_hparams:
      num_blocks:
      - 2
      - 2
      - 2
      - 2
      c_hidden:
      - 64
      - 128
      - 256
      - 512
      block_name: preact
data:
  class_path: datamodule.SUN397DataModule
  init_args:
    data_dir: ../data
    val_split_per_class: 10
    test_split_per_class: 40
    batch_size: 128
    num_workers: 0
    oversample_epoch: 60
optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 0.1
    momentum: 0.9
    dampening: 0.0
    weight_decay: 0.0002
    nesterov: false
    maximize: false
    foreach: null
    differentiable: false
lr_scheduler:
  class_path: torch.optim.lr_scheduler.MultiStepLR
  init_args:
    milestones:
    - 30
    - 60
    gamma: 0.1
    last_epoch: -1
    verbose: false
